name: Deploy Node.js App to AWS Lightsail

on:
  push:
    branches:
      - master # Or any branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v1

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '20' # Use the Node version your app requires

    - name: Install Dependencies
      run: npm install

    - name: Print HOST secret
      run: echo "HOST: ${{ secrets.HOST }}"

    - name: Print USERNAME secret
      run: echo "USERNAME: ${{ secrets.USERNAME }}"

    - name: Print SSH_PRIVATE_KEY secret
      run: echo "SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}"

    - name: Copy files to Lightsail
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        source: "."
        target: "/home/ubuntu/inventory-demo/demo-inventory-backend"

    - name: Restart Node.js app
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/ubuntu/inventory-demo/demo-inventory-backend
          npm install --production
          pm2 restart all # or your specific start command
