name: Node.js CI/CD Pipeline

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.10.0' # Specify your Node.js version

    - name: Install Dependencies
      run: npm install

    - name: Deploy to AWS Lightsail
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: 22
        KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      with:
        source: "./" # Or the path to your build artifacts
        target: "/home/ubuntu/inventory-demo/demo-inventory-backend"